export type WorkloadBand = "under-5" | "5-10" | "10-15" | "15-plus" | "20-plus";

export type CourseEvaluationReview = {
  id: string;
  professor: string;
  rating: number | null;
  lectureAttendance: string;
  lectureRecording: string;
  groupWork: string;
  labAttendance: string;
  exams: string;
  workload: string;
  workloadBand: WorkloadBand;
  summaryKo: string;
  bulletsKo: string[];
  officeHoursKo: string;
  tags: string[];
};

export type CourseEvaluationCourse = {
  id: string;
  code: string;
  department: string;
  number: string;
  title: string;
  college: string;
  summaryKo: string;
  tags: string[];
  reviews: CourseEvaluationReview[];
};

export const workloadLabels: Record<WorkloadBand, string> = {
  "under-5": "주 5시간 미만",
  "5-10": "주 5-10시간",
  "10-15": "주 10-15시간",
  "15-plus": "주 15시간+",
  "20-plus": "주 20시간+",
};

export const courseEvaluations: CourseEvaluationCourse[] = [
  {
    id: "eecs-183",
    code: "EECS 183",
    department: "EECS",
    number: "183",
    title: "Programming Concepts",
    college: "COE",
    summaryKo: "프로그래밍 입문용 수업이지만 프로젝트 비중이 커서 파트너와 시간 관리가 중요합니다.",
    tags: ["프로그래밍", "프로젝트", "C++", "입문"],
    reviews: [
      {
        id: "eecs-183-general",
        professor: "General",
        rating: 4,
        lectureAttendance: "Required",
        lectureRecording: "Available",
        groupWork: "Required",
        labAttendance: "Required",
        exams: "1 Midterm, 1 Final, No Curve",
        workload: "10-15 hrs/week",
        workloadBand: "10-15",
        summaryKo:
          "CS 경험이 있으면 수월하지만 처음 배우는 학생에게도 가능한 수업입니다. 프로젝트가 길어질 수 있어 좋은 파트너를 찾는 것이 중요합니다.",
        bulletsKo: [
          "C++ 기초와 프로그래밍 개념을 배웁니다.",
          "프로젝트는 시간이 오래 걸리므로 미리 시작하는 것이 좋습니다.",
          "AP CSA 경험이 있으면 초반 적응이 쉽습니다.",
        ],
        officeHoursKo: "Office hour는 자주 열리며 프로젝트 기간에 활용도가 높습니다.",
        tags: ["프로젝트 많음", "녹화 있음", "입문"],
      },
    ],
  },
  {
    id: "eecs-203",
    code: "EECS 203",
    department: "EECS",
    number: "203",
    title: "Discrete Mathematics",
    college: "COE",
    summaryKo: "EECS 376의 기반이 되는 이산수학 수업으로, 숙제와 증명 사고에 시간을 꾸준히 써야 합니다.",
    tags: ["이산수학", "증명", "필수", "숙제"],
    reviews: [
      {
        id: "eecs-203-general",
        professor: "General",
        rating: 4,
        lectureAttendance: "Not Required",
        lectureRecording: "Available",
        groupWork: "Required",
        labAttendance: "Discussion Not Required",
        exams: "3 Midterms, Curved",
        workload: "10-15 hrs/week",
        workloadBand: "10-15",
        summaryKo:
          "숙제 난이도와 시험 준비량이 있는 편입니다. 376을 듣기 전에 개념을 제대로 잡아두면 도움이 됩니다.",
        bulletsKo: [
          "숙제는 보통 4-5시간 이상 걸릴 수 있습니다.",
          "고득점을 목표로 하면 더 많은 시간이 필요합니다.",
          "North Campus와 Shapiro 쪽 OH를 활용하면 좋습니다.",
        ],
        officeHoursKo: "Office hour가 자주 열리며 문제 풀이에 도움을 받기 좋습니다.",
        tags: ["필수", "녹화 있음", "증명"],
      },
    ],
  },
  {
    id: "eecs-280",
    code: "EECS 280",
    department: "EECS",
    number: "280",
    title: "Programming and Introductory Data Structures",
    college: "COE",
    summaryKo: "자료구조와 C++ 프로젝트 중심 수업으로 EECS 트랙에서 가장 중요한 초반 관문 중 하나입니다.",
    tags: ["자료구조", "C++", "프로젝트", "필수"],
    reviews: [
      {
        id: "eecs-280-general",
        professor: "Juett / DeOrio / Beaumont",
        rating: 4,
        lectureAttendance: "Not Required",
        lectureRecording: "Available",
        groupWork: "Required",
        labAttendance: "Required",
        exams: "1 Midterm, 1 Final, Curved",
        workload: "10-15 hrs/week",
        workloadBand: "10-15",
        summaryKo:
          "프로젝트가 핵심입니다. 시작을 늦추면 부담이 크게 늘어나므로 일정 관리가 가장 중요합니다.",
        bulletsKo: [
          "프로젝트 난이도와 디버깅 시간이 큽니다.",
          "Lab과 discussion 자료를 놓치지 않는 것이 좋습니다.",
          "파트너 프로젝트에서는 소통과 역할 분담이 중요합니다.",
        ],
        officeHoursKo: "프로젝트 기간에는 OH가 매우 유용하지만 대기가 길 수 있습니다.",
        tags: ["프로젝트 많음", "녹화 있음", "중요"],
      },
    ],
  },
  {
    id: "eecs-281",
    code: "EECS 281",
    department: "EECS",
    number: "281",
    title: "Data Structures and Algorithms",
    college: "COE",
    summaryKo: "알고리즘과 자료구조를 깊게 다루는 핵심 수업으로 프로젝트와 시험 모두 준비가 필요합니다.",
    tags: ["알고리즘", "자료구조", "프로젝트", "필수"],
    reviews: [
      {
        id: "eecs-281-general",
        professor: "DeOrio / Paoletti / Juett / Darden",
        rating: 4,
        lectureAttendance: "Not Required",
        lectureRecording: "Available",
        groupWork: "None",
        labAttendance: "Required",
        exams: "1 Midterm, 1 Final",
        workload: "10-15 hrs/week",
        workloadBand: "10-15",
        summaryKo:
          "EECS 전공생들이 많이 어렵다고 느끼는 수업입니다. Studio 녹화와 프로젝트 시작 타이밍이 중요합니다.",
        bulletsKo: [
          "프로젝트를 일찍 시작하는 것이 가장 중요합니다.",
          "시험은 개념 이해와 구현 감각이 같이 필요합니다.",
          "Studio 자료와 녹화를 적극 활용하는 것을 추천합니다.",
        ],
        officeHoursKo: "프로젝트와 시험 전 OH 수요가 많으니 일찍 가는 편이 좋습니다.",
        tags: ["난이도 높음", "녹화 있음", "프로젝트"],
      },
    ],
  },
  {
    id: "eecs-370",
    code: "EECS 370",
    department: "EECS",
    number: "370",
    title: "Introduction to Computer Organization",
    college: "COE",
    summaryKo: "컴퓨터 구조를 배우며 프로젝트와 lab이 있는 수업입니다. 281과 동시에 듣는 것은 부담이 될 수 있습니다.",
    tags: ["컴퓨터구조", "프로젝트", "Lab", "상급"],
    reviews: [
      {
        id: "eecs-370-general",
        professor: "General",
        rating: 4,
        lectureAttendance: "Not Required",
        lectureRecording: "Available",
        groupWork: "Required",
        labAttendance: "Required",
        exams: "1 Midterm, 1 Final, Not Curved",
        workload: "About 10 hrs/week",
        workloadBand: "10-15",
        summaryKo:
          "4개 프로젝트와 lab, homework가 있어 꾸준히 해야 합니다. 281과 같이 듣는 것은 추천하지 않는다는 후기가 있습니다.",
        bulletsKo: [
          "프로젝트와 lab 준비가 학기 내내 이어집니다.",
          "개념이 쌓이는 구조라 초반을 놓치면 뒤가 어려워집니다.",
          "동시 수강 과목 조합을 조심하는 것이 좋습니다.",
        ],
        officeHoursKo: "프로젝트 디버깅 단계에서 OH를 활용하는 것이 좋습니다.",
        tags: ["녹화 있음", "프로젝트", "상급"],
      },
    ],
  },
  {
    id: "eecs-376",
    code: "EECS 376",
    department: "EECS",
    number: "376",
    title: "Foundations of Computer Science",
    college: "COE",
    summaryKo: "203보다 더 깊은 이론/알고리즘 사고를 요구하는 수업으로 증명과 개념 이해가 중요합니다.",
    tags: ["이론", "알고리즘", "증명", "상급"],
    reviews: [
      {
        id: "eecs-376-general",
        professor: "General",
        rating: 4,
        lectureAttendance: "Required",
        lectureRecording: "Available",
        groupWork: "None",
        labAttendance: "Not Required",
        exams: "1 Midterm, 1 Final, No Curve",
        workload: "About 10 hrs/week",
        workloadBand: "10-15",
        summaryKo:
          "203보다 어렵게 느껴질 수 있고, 알고리즘 원리와 증명 감각이 중요합니다.",
        bulletsKo: [
          "문제 풀이를 미루지 않는 것이 중요합니다.",
          "203 내용이 약하면 초반부터 복습이 필요합니다.",
          "시험 대비는 개념 정리와 문제 풀이를 같이 해야 합니다.",
        ],
        officeHoursKo: "Office hour가 자주 있어 어려운 문제를 들고 가기 좋습니다.",
        tags: ["난이도 높음", "녹화 있음", "증명"],
      },
    ],
  },
  {
    id: "eecs-485",
    code: "EECS 485",
    department: "EECS",
    number: "485",
    title: "Web Systems",
    college: "COE",
    summaryKo: "웹 시스템을 프로젝트 중심으로 배우는 수업입니다. 실용성이 높고 첫 ULCS로 추천된다는 후기가 있습니다.",
    tags: ["웹", "프로젝트", "ULCS", "실용"],
    reviews: [
      {
        id: "eecs-485-general",
        professor: "DeOrio",
        rating: 5,
        lectureAttendance: "Not Required",
        lectureRecording: "Available",
        groupWork: "Required",
        labAttendance: "Not Required",
        exams: "1 Midterm, 1 Final, Curved",
        workload: "10-15 hrs/week",
        workloadBand: "10-15",
        summaryKo:
          "프로젝트가 길지만 배운 것이 실제로 남는 수업이라는 평가가 있습니다. 웹 개발 경험을 쌓기 좋습니다.",
        bulletsKo: [
          "프로젝트가 중심이고 마감 전 몰리면 매우 바쁩니다.",
          "웹 시스템 구조를 실습으로 익힐 수 있습니다.",
          "첫 ULCS로 고려할 만하다는 후기가 있습니다.",
        ],
        officeHoursKo: "프로젝트 진행 중 막히는 부분을 들고 가면 도움이 됩니다.",
        tags: ["프로젝트 많음", "녹화 있음", "추천"],
      },
    ],
  },
  {
    id: "econ-101",
    code: "ECON 101",
    department: "ECON",
    number: "101",
    title: "Principles of Economics I",
    college: "LSA",
    summaryKo: "경제학 입문 수업이지만 시험 문항 표현이 까다로울 수 있어 연습문제가 중요합니다.",
    tags: ["경제학", "입문", "시험", "LSA"],
    reviews: [
      {
        id: "econ-101-general",
        professor: "Caldwell / Wolfers",
        rating: 4,
        lectureAttendance: "Not Required",
        lectureRecording: "Available",
        groupWork: "None",
        labAttendance: "Discussion",
        exams: "2 Midterms, 1 Final, Curved",
        workload: "5-10 hrs/week",
        workloadBand: "5-10",
        summaryKo:
          "입문 수업이지만 시험이 단순 암기형은 아닙니다. 퀴즈와 past exam을 잘 보는 것이 좋습니다.",
        bulletsKo: [
          "경제학을 처음 접하는 학생에게 적합합니다.",
          "시험 문제 wording에 익숙해지는 것이 중요합니다.",
          "Review quiz와 practice exam을 추천합니다.",
        ],
        officeHoursKo: "GSI/교수 OH 모두 시험 전 활용하기 좋습니다.",
        tags: ["녹화 있음", "입문", "인기"],
      },
    ],
  },
  {
    id: "econ-102",
    code: "ECON 102",
    department: "ECON",
    number: "102",
    title: "Principles of Economics II",
    college: "LSA",
    summaryKo: "거시경제 입문 수업으로 과제와 시험 준비가 꾸준히 필요합니다.",
    tags: ["경제학", "거시", "입문", "과제"],
    reviews: [
      {
        id: "econ-102-general",
        professor: "General",
        rating: 3,
        lectureAttendance: "Not Required",
        lectureRecording: "Available",
        groupWork: "None",
        labAttendance: "Discussion",
        exams: "2 Midterms, 1 Final, Curved",
        workload: "5-10 hrs/week",
        workloadBand: "5-10",
        summaryKo:
          "거시경제를 배우며 homework와 article response가 있습니다. 워크로드를 피하고 싶은 학생에게는 가볍지만은 않습니다.",
        bulletsKo: [
          "6개 정도의 homework/article response가 언급됩니다.",
          "Econ 전공/부전공 계획이 있으면 기본기로 좋습니다.",
          "시험 준비를 몰아서 하기보다는 꾸준히 하는 편이 좋습니다.",
        ],
        officeHoursKo: "시험 전 개념 질문을 정리해서 가면 좋습니다.",
        tags: ["녹화 있음", "과제", "거시"],
      },
    ],
  },
  {
    id: "econ-401",
    code: "ECON 401",
    department: "ECON",
    number: "401",
    title: "Intermediate Microeconomic Theory",
    college: "LSA",
    summaryKo: "중급 미시 수업으로 시험 비중이 크고 첫 시험이 중요하다는 후기가 있습니다.",
    tags: ["미시경제", "중급", "시험", "전공"],
    reviews: [
      {
        id: "econ-401-general",
        professor: "General",
        rating: 4,
        lectureAttendance: "Not Required",
        lectureRecording: "Available",
        groupWork: "None",
        labAttendance: "Discussion",
        exams: "2 Midterms, 1 Final, Curved",
        workload: "5-10 hrs/week",
        workloadBand: "5-10",
        summaryKo:
          "시험 대비가 가장 중요합니다. Practice problem을 많이 풀고 첫 시험을 잘 보는 것이 좋습니다.",
        bulletsKo: [
          "중급 미시 개념과 수식 활용이 필요합니다.",
          "첫 exam 성적이 체감 난이도에 영향을 크게 줍니다.",
          "Practice problem 중심으로 공부하는 것을 추천합니다.",
        ],
        officeHoursKo: "문제 풀이 과정에서 막히는 부분을 들고 가면 좋습니다.",
        tags: ["녹화 있음", "시험 중요", "전공"],
      },
    ],
  },
  {
    id: "math-115",
    code: "MATH 115",
    department: "MATH",
    number: "115",
    title: "Calculus I",
    college: "LSA",
    summaryKo: "미적분 입문이지만 출석과 숙제, 시험 준비량이 있어 꾸준함이 필요합니다.",
    tags: ["미적분", "입문", "숙제", "필수"],
    reviews: [
      {
        id: "math-115-general",
        professor: "General",
        rating: 4,
        lectureAttendance: "Required",
        lectureRecording: "Unavailable",
        groupWork: "Required",
        labAttendance: "Discussion",
        exams: "2 Midterms, 1 Final, Curved",
        workload: "10-15 hrs/week",
        workloadBand: "10-15",
        summaryKo:
          "Weekly homework와 시험 대비가 중요합니다. Mastery와 past exam을 적극 활용하는 것을 추천합니다.",
        bulletsKo: [
          "주당 강의/토론 시간이 꽤 있고 숙제도 꾸준합니다.",
          "Weekly homework는 5-7시간 정도 걸릴 수 있습니다.",
          "시험 전 past exam으로 문제 유형을 익히는 것이 좋습니다.",
        ],
        officeHoursKo: "문제 풀이 질문을 들고 가면 도움이 됩니다.",
        tags: ["출석 필요", "녹화 없음", "숙제"],
      },
    ],
  },
  {
    id: "math-116",
    code: "MATH 116",
    department: "MATH",
    number: "116",
    title: "Calculus II",
    college: "LSA",
    summaryKo: "Calculus II는 난이도와 숙제량이 있어 시험 준비를 일찍 시작하는 것이 좋습니다.",
    tags: ["미적분", "숙제", "시험", "필수"],
    reviews: [
      {
        id: "math-116-general",
        professor: "General",
        rating: 4,
        lectureAttendance: "Not Required",
        lectureRecording: "Unavailable",
        groupWork: "Required",
        labAttendance: "Discussion",
        exams: "2 Midterms, 1 Final, Curved",
        workload: "10-15 hrs/week",
        workloadBand: "10-15",
        summaryKo:
          "Group homework와 weekly work가 있습니다. 시험은 최소 일주일 전부터 준비하는 편이 좋습니다.",
        bulletsKo: [
          "Group homework가 체감 워크로드에 영향을 줍니다.",
          "주당 5시간 이상 숙제 시간이 필요할 수 있습니다.",
          "시험 직전 몰아서 하기에는 부담이 큽니다.",
        ],
        officeHoursKo: "어려운 문제를 미리 체크해 OH에서 확인하는 것이 좋습니다.",
        tags: ["녹화 없음", "숙제", "시험"],
      },
    ],
  },
  {
    id: "math-215",
    code: "MATH 215",
    department: "MATH",
    number: "215",
    title: "Calculus III",
    college: "LSA",
    summaryKo: "Multivariable calculus 수업으로 written homework와 web homework 모두 시간이 꽤 걸립니다.",
    tags: ["다변수", "숙제", "난이도", "수학"],
    reviews: [
      {
        id: "math-215-general",
        professor: "General",
        rating: 3,
        lectureAttendance: "Not Required",
        lectureRecording: "Unavailable",
        groupWork: "Required",
        labAttendance: "Required",
        exams: "2 Midterms, 1 Final, Curved",
        workload: "10-15 hrs/week",
        workloadBand: "10-15",
        summaryKo:
          "Written homework만 6시간 이상 걸릴 수 있다는 후기가 있습니다. 개념이 어렵게 느껴지면 외부 자료도 도움이 됩니다.",
        bulletsKo: [
          "Written homework와 web homework가 모두 있습니다.",
          "Korean YouTube 등 보충 자료가 도움이 된다는 후기가 있습니다.",
          "시험 전 문제 유형을 충분히 반복해야 합니다.",
        ],
        officeHoursKo: "숙제 문제를 들고 가면 도움이 됩니다.",
        tags: ["녹화 없음", "난이도 높음", "숙제"],
      },
    ],
  },
  {
    id: "math-217",
    code: "MATH 217",
    department: "MATH",
    number: "217",
    title: "Linear Algebra",
    college: "LSA",
    summaryKo: "Proof-heavy한 flipped/IBL 스타일 수업으로 수학 전공/부전공이나 proof 관심이 있을 때 추천됩니다.",
    tags: ["선형대수", "Proof", "난이도 높음", "수학"],
    reviews: [
      {
        id: "math-217-general",
        professor: "General",
        rating: 3,
        lectureAttendance: "Required",
        lectureRecording: "Unavailable",
        groupWork: "None",
        labAttendance: "Discussion",
        exams: "2 Midterms, 1 Final, Not Curved",
        workload: "20+ hrs/week",
        workloadBand: "20-plus",
        summaryKo:
          "IBL/Flipped 방식이라 스스로 준비하고 증명을 익혀야 합니다. 가벼운 선형대수를 기대하면 힘들 수 있습니다.",
        bulletsKo: [
          "Proof 중심이라 일반 계산형 선형대수와 다릅니다.",
          "수학 minor/major 또는 proof 관심 학생에게 더 적합합니다.",
          "워크로드가 매우 높다는 후기가 있습니다.",
        ],
        officeHoursKo: "Proof 사고가 막힐 때 자주 활용하는 것이 좋습니다.",
        tags: ["출석 필요", "녹화 없음", "매우 어려움"],
      },
    ],
  },
  {
    id: "stats-250",
    code: "STATS 250",
    department: "STATS",
    number: "250",
    title: "Introduction to Statistics and Data Analysis",
    college: "LSA",
    summaryKo: "통계 입문 수업으로 R lab과 homework가 있으며 밀리지 않으면 관리 가능한 편입니다.",
    tags: ["통계", "R", "입문", "데이터"],
    reviews: [
      {
        id: "stats-250-general",
        professor: "General",
        rating: 4,
        lectureAttendance: "Optional",
        lectureRecording: "Available",
        groupWork: "None",
        labAttendance: "Not Required",
        exams: "1 Midterm, 1 Final, Not Curved",
        workload: "5-10 hrs/week",
        workloadBand: "5-10",
        summaryKo:
          "R lab과 숙제가 있지만 입문용으로 괜찮다는 평가입니다. 단, 내용을 밀리면 따라가기 어려울 수 있습니다.",
        bulletsKo: [
          "R을 사용한 lab/homework가 있습니다.",
          "숙제는 보통 3-4시간 정도 걸릴 수 있습니다.",
          "기초 통계를 처음 접하기에 적합합니다.",
        ],
        officeHoursKo: "R lab이나 homework 질문을 들고 가면 좋습니다.",
        tags: ["녹화 있음", "입문", "R"],
      },
    ],
  },
  {
    id: "stats-412",
    code: "STATS 412",
    department: "STATS",
    number: "412",
    title: "Introduction to Probability and Statistics",
    college: "LSA",
    summaryKo: "확률/통계 수업으로 시험과 equation sheet 준비가 중요합니다.",
    tags: ["확률", "통계", "시험", "전공"],
    reviews: [
      {
        id: "stats-412-general",
        professor: "Hsing / Fink",
        rating: 3,
        lectureAttendance: "Not Required",
        lectureRecording: "Available",
        groupWork: "None",
        labAttendance: "N/A",
        exams: "3 Exams",
        workload: "5-10 hrs/week",
        workloadBand: "5-10",
        summaryKo:
          "교수에 따라 체감이 갈릴 수 있습니다. Equation sheet를 잘 준비하고 문제 풀이를 반복하는 것이 중요합니다.",
        bulletsKo: [
          "Hsing 교수는 도움이 된다는 후기가 있습니다.",
          "Fink 교수는 피하라는 후기가 있었습니다.",
          "시험 대비용 공식 정리와 문제 풀이가 중요합니다.",
        ],
        officeHoursKo: "개념과 문제풀이를 같이 확인하기 좋습니다.",
        tags: ["녹화 있음", "시험", "확률"],
      },
    ],
  },
  {
    id: "datasci-306",
    code: "DATASCI 306",
    department: "DATASCI",
    number: "306",
    title: "Introduction to Statistical Computing",
    college: "LSA",
    summaryKo: "R 코딩 중심 수업으로 입문처럼 보여도 작업량이 꽤 있다는 후기가 있습니다.",
    tags: ["데이터", "R", "코딩", "통계"],
    reviews: [
      {
        id: "datasci-306-general",
        professor: "General",
        rating: 3,
        lectureAttendance: "Not Required",
        lectureRecording: "Available",
        groupWork: "Required",
        labAttendance: "Not Required",
        exams: "3 Exams",
        workload: "5-10 hrs/week",
        workloadBand: "5-10",
        summaryKo:
          "R을 많이 사용하며 intro class처럼 보여도 생각보다 과제가 있습니다. 교수 선택에 대한 후기도 갈립니다.",
        bulletsKo: [
          "R coding 비중이 큽니다.",
          "Intro보다 heavier하다는 후기가 있습니다.",
          "교수/섹션 정보를 확인하고 수강하는 것이 좋습니다.",
        ],
        officeHoursKo: "코딩 에러나 과제 질문을 들고 가면 좋습니다.",
        tags: ["녹화 있음", "R", "코딩"],
      },
    ],
  },
  {
    id: "ioe-201",
    code: "IOE 201",
    department: "IOE",
    number: "201",
    title: "Economic Decision Making",
    college: "COE",
    summaryKo: "경제적 의사결정/공학경제 성격의 수업으로 과제와 프로젝트가 있어 과소평가하지 않는 것이 좋습니다.",
    tags: ["IOE", "의사결정", "프로젝트", "공학"],
    reviews: [
      {
        id: "ioe-201-general",
        professor: "General",
        rating: 4,
        lectureAttendance: "Not Required",
        lectureRecording: "Available",
        groupWork: "Project",
        labAttendance: "N/A",
        exams: "1 Final",
        workload: "5-10 hrs/week",
        workloadBand: "5-10",
        summaryKo:
          "생각보다 할 일이 있는 수업입니다. Assignment와 group project, final이 있으므로 꾸준히 관리해야 합니다.",
        bulletsKo: [
          "과제와 group project가 있습니다.",
          "내용을 쉽게 보고 미루면 부담이 커질 수 있습니다.",
          "IOE 학생에게 기본기로 유용합니다.",
        ],
        officeHoursKo: "과제 계산이나 프로젝트 방향을 확인하기 좋습니다.",
        tags: ["녹화 있음", "프로젝트", "IOE"],
      },
    ],
  },
  {
    id: "ioe-265",
    code: "IOE 265",
    department: "IOE",
    number: "265",
    title: "Probability and Statistics for Engineers",
    college: "COE",
    summaryKo: "공대 확률/통계 수업으로 비교적 manageable하다는 후기가 있습니다.",
    tags: ["IOE", "확률", "통계", "공학"],
    reviews: [
      {
        id: "ioe-265-general",
        professor: "General",
        rating: 4,
        lectureAttendance: "Required",
        lectureRecording: "Available",
        groupWork: "None",
        labAttendance: "N/A",
        exams: "2 Midterms, 1 Final",
        workload: "Under 5 hrs/week",
        workloadBand: "under-5",
        summaryKo:
          "전반적으로 쉬운 편이라는 후기가 있습니다. 온라인 시험과 비교적 낮은 워크로드가 언급됩니다.",
        bulletsKo: [
          "온라인 시험이 48시간 열렸다는 후기가 있습니다.",
          "공대 통계 기본기를 잡기 좋습니다.",
          "낮은 워크로드 수업으로 언급됩니다.",
        ],
        officeHoursKo: "시험 전 개념 확인용으로 활용하면 좋습니다.",
        tags: ["녹화 있음", "워크로드 낮음", "공대"],
      },
    ],
  },
  {
    id: "comm-102",
    code: "COMM 102",
    department: "COMM",
    number: "102",
    title: "Media Processes and Effects",
    college: "LSA",
    summaryKo: "미디어/커뮤니케이션 입문 수업으로 온라인 오픈북 시험과 outline 과제가 언급됩니다.",
    tags: ["COMM", "미디어", "입문", "LSA"],
    reviews: [
      {
        id: "comm-102-general",
        professor: "General",
        rating: 4,
        lectureAttendance: "Required",
        lectureRecording: "Unavailable",
        groupWork: "None",
        labAttendance: "Required",
        exams: "1 Midterm, 1 Final, Not Curved",
        workload: "About 5 hrs/week",
        workloadBand: "5-10",
        summaryKo:
          "Attendance가 중요하고 시험은 온라인/open-book 형태라는 후기가 있습니다. Outline assignment가 도움이 됩니다.",
        bulletsKo: [
          "Lecture/discussion 참여가 중요합니다.",
          "시험은 온라인 open-book으로 언급됩니다.",
          "Outline assignment를 잘 활용하면 시험 대비에 도움이 됩니다.",
        ],
        officeHoursKo: "과제 방향을 확인할 때 활용하면 좋습니다.",
        tags: ["출석 필요", "녹화 없음", "입문"],
      },
    ],
  },
  {
    id: "psych-111",
    code: "PSYCH 111",
    department: "PSYCH",
    number: "111",
    title: "Introduction to Psychology",
    college: "LSA",
    summaryKo: "심리학 입문 수업으로 암기량이 있지만 워크로드는 비교적 낮다는 후기가 있습니다.",
    tags: ["심리학", "입문", "암기", "LSA"],
    reviews: [
      {
        id: "psych-111-general",
        professor: "General",
        rating: 4,
        lectureAttendance: "Not Required",
        lectureRecording: "Unavailable",
        groupWork: "None",
        labAttendance: "Required",
        exams: "5+ Quizzes, 3 Midterms",
        workload: "Under 5 hrs/week",
        workloadBand: "under-5",
        summaryKo:
          "암기할 내용은 많지만 extra credit과 quiz 구조를 잘 활용하면 관리 가능한 수업입니다.",
        bulletsKo: [
          "심리학을 처음 접하기 좋은 입문 수업입니다.",
          "용어와 개념 암기가 중요합니다.",
          "Extra credit 기회를 확인하는 것이 좋습니다.",
        ],
        officeHoursKo: "시험 전 개념 정리용으로 활용하면 좋습니다.",
        tags: ["워크로드 낮음", "입문", "암기"],
      },
    ],
  },
  {
    id: "asian-274",
    code: "ASIAN 274",
    department: "ASIAN",
    number: "274",
    title: "Introduction to Korean Civilization",
    college: "LSA",
    summaryKo: "한국사/한국문명 관련 수업으로 쉽고 재미있다는 추천 후기가 있습니다.",
    tags: ["한국", "교양", "LSA", "추천"],
    reviews: [
      {
        id: "asian-274-general",
        professor: "Ahn, Junh",
        rating: 5,
        lectureAttendance: "Optional",
        lectureRecording: "Unavailable",
        groupWork: "None",
        labAttendance: "Not Required",
        exams: "2 Quizzes, 2 Projects",
        workload: "Under 5 hrs/week",
        workloadBand: "under-5",
        summaryKo:
          "한국사에 관심이 있으면 부담 없이 듣기 좋다는 후기가 있습니다. 워크로드가 낮은 편으로 언급됩니다.",
        bulletsKo: [
          "한국 문명/역사를 다루는 교양 수업입니다.",
          "Quiz와 project가 있지만 워크로드가 낮은 편입니다.",
          "KISA 학생들에게 친숙한 주제라 접근하기 좋습니다.",
        ],
        officeHoursKo: "필요할 때 교수님께 컨택하면 됩니다.",
        tags: ["워크로드 낮음", "한국", "추천"],
      },
    ],
  },
];

export const courseDepartments = Array.from(
  new Set(courseEvaluations.map((course) => course.department)),
).sort();

export const courseColleges = Array.from(
  new Set(courseEvaluations.map((course) => course.college)),
).sort();
