export type KisaPickCategory =
  | "restaurant"
  | "cafe"
  | "store"
  | "drinks"
  | "things";

export type KisaPick = {
  id: string;
  name: string;
  category: KisaPickCategory;
  cuisine?: string;
  area: string;
  lat: number;
  lng: number;
  note: string;
  whatToOrder?: string[];
  tags: string[];
  image: string;
  mapsUrl: string;
};

export const categoryLabels: Record<KisaPickCategory, string> = {
  restaurant: "Restaurant",
  cafe: "Cafe",
  store: "Store",
  drinks: "Drinks / Bar",
  things: "Things to do",
};

export const kisaPicks: KisaPick[] = [
  {
    id: "tomukun_bbq",
    name: "Tomukun BBQ",
    category: "restaurant",
    cuisine: "Korean",
    area: "South University",
    lat: 42.2795276,
    lng: -83.7427536,
    note: "Reliable Korean BBQ and comfort food close to Central Campus.",
    whatToOrder: ["Korean BBQ set", "Kimchi stew", "Seafood pancake"],
    tags: ["Korean", "Group meal", "Central"],
    image: "/images/tomukun_bbq.webp",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Tomukun+BBQ+Ann+Arbor",
  },
  {
    id: "tomukun_noodle_bar",
    name: "Tomukun Noodle Bar",
    category: "restaurant",
    cuisine: "Asian",
    area: "South University",
    lat: 42.2795276,
    lng: -83.7427536,
    note: "Easy campus ramen/noodle stop when you want something warm and quick.",
    whatToOrder: ["Tonkotsu ramen", "Miso ramen", "Bao or small plates"],
    tags: ["Noodles", "Casual", "Central"],
    image: "/images/tomukun_noodle_bar.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Tomukun+Noodle+Bar+Ann+Arbor",
  },
  {
    id: "hola_seoul",
    name: "Hola Seoul",
    category: "restaurant",
    cuisine: "Korean",
    area: "Central Campus",
    lat: 42.2787459,
    lng: -83.7399654,
    note: "Small spot with popcorn chicken, bento boxes, and easy Korean-style meals.",
    whatToOrder: ["Popcorn chicken", "Bento box", "Bibimbap-style bowl"],
    tags: ["Korean", "Quick bite", "Casual"],
    image: "/images/hola_seoul.webp",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Hola+Seoul+Ann+Arbor",
  },
  {
    id: "seoul_garden",
    name: "Seoul Garden",
    category: "restaurant",
    cuisine: "Korean",
    area: "South Ann Arbor",
    lat: 42.2422043,
    lng: -83.733998,
    note: "A farther Korean BBQ option when the group is willing to drive.",
    whatToOrder: ["Korean BBQ", "Bulgogi", "Soondubu"],
    tags: ["Korean", "BBQ", "Worth the trip"],
    image: "/images/seoul_garden.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Seoul+Garden+Ann+Arbor",
  },
  {
    id: "mama_satto",
    name: "Mama Satto",
    category: "restaurant",
    cuisine: "Japanese",
    area: "Central Campus",
    lat: 42.2787451,
    lng: -83.7400547,
    note: "Student-friendly Japanese/Korean-leaning comfort food near North University.",
    whatToOrder: ["Bibimbap", "Udon", "Teriyaki bowl"],
    tags: ["Japanese", "Korean", "Central"],
    image: "/images/mama_satto.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Mama+Satto+Ann+Arbor",
  },
  {
    id: "kangs_restaurant",
    name: "Kang's Restaurant",
    category: "restaurant",
    cuisine: "Korean",
    area: "South University",
    lat: 42.2751505,
    lng: -83.7323054,
    note: "Classic South U Korean comfort food with generous portions.",
    whatToOrder: ["Bulgogi", "Kimchi fried rice", "Soon tofu"],
    tags: ["Korean", "South U", "Casual"],
    image: "/images/kangs_restaurant.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Kang%27s+Restaurant+Ann+Arbor",
  },
  {
    id: "noori_chicken",
    name: "Noori Chicken",
    category: "restaurant",
    cuisine: "Korean",
    area: "South University",
    lat: 42.2751514,
    lng: -83.7324922,
    note: "Korean fried chicken close to South U; good for casual group food.",
    whatToOrder: ["Soy garlic chicken", "Spicy chicken", "Shareable wings"],
    tags: ["Korean", "Chicken", "South U"],
    image: "/images/noori_chicken.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Noori+Chicken+Ann+Arbor",
  },
  {
    id: "orange_market",
    name: "Orange Market",
    category: "store",
    cuisine: "Korean",
    area: "North of Campus",
    lat: 42.2897924,
    lng: -83.7376753,
    note: "Korean market for groceries, pantry staples, and prepared side dishes.",
    whatToOrder: ["Banchan", "Instant ramen", "Korean snacks"],
    tags: ["Korean market", "Groceries", "Essentials"],
    image: "/images/orange_market.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Orange+Market+Ann+Arbor",
  },
  {
    id: "no_thai",
    name: "No Thai!",
    category: "restaurant",
    cuisine: "Thai",
    area: "Central / Kerrytown / North",
    lat: 42.2830279,
    lng: -83.7467198,
    note: "Good value Thai food with multiple Ann Arbor locations.",
    whatToOrder: ["Pad thai", "Drunken noodles", "Curry bowl"],
    tags: ["Thai", "Value", "Multi-location"],
    image: "/images/no_thai.webp",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No+Thai+Ann+Arbor",
  },
  {
    id: "kanbu",
    name: "Kanbu",
    category: "restaurant",
    cuisine: "Japanese",
    area: "South Ann Arbor",
    lat: 42.2446818,
    lng: -83.7375348,
    note: "Sushi burritos and casual Japanese options south of campus.",
    whatToOrder: ["Sushi burrito", "Poke-style bowl", "Tempura side"],
    tags: ["Japanese", "Sushi", "Worth the trip"],
    image: "/images/kanbu.webp",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Kanbu+Ann+Arbor",
  },
  {
    id: "evergreen",
    name: "Evergreen",
    category: "restaurant",
    cuisine: "Chinese",
    area: "North Campus / Plymouth",
    lat: 42.3037636,
    lng: -83.7058163,
    note: "North-side Chinese restaurant near Plymouth Road.",
    whatToOrder: ["Mapo tofu", "Noodle dish", "Shareable family-style plates"],
    tags: ["Chinese", "North Campus", "Worth the trip"],
    image: "/images/evergreen.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Evergreen+Restaurant+Ann+Arbor",
  },
  {
    id: "asian_legend",
    name: "Asian Legend",
    category: "restaurant",
    cuisine: "Chinese",
    area: "Central Campus",
    lat: 42.2777316,
    lng: -83.7424327,
    note: "Close-to-campus Chinese option with a practical, student-friendly feel.",
    whatToOrder: ["Fried rice", "Noodle soup", "Shareable entree"],
    tags: ["Chinese", "Near Diag", "Casual"],
    image: "/images/asian_legend.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Asian+Legend+Ann+Arbor",
  },
  {
    id: "slurping_turtle",
    name: "Slurping Turtle",
    category: "restaurant",
    cuisine: "Japanese",
    area: "Downtown",
    lat: 42.2792719,
    lng: -83.7416011,
    note: "Downtown ramen and Japanese small plates close to Central Campus.",
    whatToOrder: ["Ramen", "Duck fat fried chicken", "Small plates"],
    tags: ["Japanese", "Ramen", "Downtown"],
    image: "/images/slurping_turtle.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Slurping+Turtle+Ann+Arbor",
  },
  {
    id: "frita_batidos",
    name: "Frita Batidos",
    category: "restaurant",
    cuisine: "Cuban",
    area: "Downtown",
    lat: 42.2804063,
    lng: -83.7493606,
    note: "Downtown Cuban-inspired burgers and batidos; better for a planned meal.",
    whatToOrder: ["Frita burger", "Batido", "Loaded fries"],
    tags: ["Downtown", "Burger", "Date spot"],
    image: "/images/frita_batidos.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Frita+Batidos+Ann+Arbor",
  },
  {
    id: "joes_pizza",
    name: "Joe's Pizza",
    category: "restaurant",
    cuisine: "Pizza",
    area: "South University",
    lat: 42.2752067,
    lng: -83.7356682,
    note: "NY-style slices near campus; easy late-day food move.",
    whatToOrder: ["Cheese slice", "Pepperoni slice", "White slice"],
    tags: ["Pizza", "Quick bite", "Central"],
    image: "/images/joes_pizza.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Joe%27s+Pizza+Ann+Arbor",
  },
  {
    id: "blank_slate",
    name: "Blank Slate",
    category: "cafe",
    cuisine: "Dessert",
    area: "Kerrytown",
    lat: 42.2797193,
    lng: -83.7513535,
    note: "Ann Arbor ice cream staple with a lot of flavors; worth the walk.",
    whatToOrder: ["Seasonal scoop", "Waffle cone", "Split a flight"],
    tags: ["Dessert", "Kerrytown", "Date spot"],
    image: "/images/blank_slate.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Blank+Slate+Ann+Arbor",
  },
  {
    id: "milk_and_froth",
    name: "Milk & Froth",
    category: "cafe",
    cuisine: "Dessert",
    area: "Downtown",
    lat: 42.2801,
    lng: -83.7481,
    note: "Downtown ice cream stop for dessert after dinner.",
    whatToOrder: ["Seasonal scoop", "Milkshake", "Two-flavor cup"],
    tags: ["Dessert", "Downtown", "Ice cream"],
    image: "/images/milk_and_froth.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Milk+and+Froth+Ann+Arbor",
  },
  {
    id: "sweeting",
    name: "Sweeting",
    category: "cafe",
    cuisine: "Dessert",
    area: "South University",
    lat: 42.27535,
    lng: -83.73515,
    note: "Bubble tea and dessert near South University.",
    whatToOrder: ["Milk tea", "Fruit tea", "Dessert cup"],
    tags: ["Dessert", "Boba", "South U"],
    image: "/images/sweeting.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Sweeting+1205+South+University+Ann+Arbor",
  },
  {
    id: "comet_coffee",
    name: "Comet Coffee",
    category: "cafe",
    cuisine: "Coffee",
    area: "Nickels Arcade",
    lat: 42.2784432,
    lng: -83.7412937,
    note: "Small coffee stop tucked into Nickels Arcade; best for slow campus breaks.",
    whatToOrder: ["Pour-over", "Espresso drink", "Pastry"],
    tags: ["Coffee", "Study break", "Central"],
    image: "/images/comet_coffee.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Comet+Coffee+Ann+Arbor",
  },
  {
    id: "savas",
    name: "Sava's",
    category: "restaurant",
    cuisine: "American",
    area: "State Street",
    lat: 42.2796696,
    lng: -83.7410006,
    note: "More polished sit-down option right by campus.",
    whatToOrder: ["Brunch plate", "Pasta or bowl", "Shared appetizer"],
    tags: ["Sit-down", "State Street", "Brunch"],
    image: "/images/savas.webp",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Sava%27s+Ann+Arbor",
  },
  {
    id: "aventura",
    name: "Aventura",
    category: "restaurant",
    cuisine: "Spanish",
    area: "Downtown",
    lat: 42.2803277,
    lng: -83.7465775,
    note: "Polished downtown tapas and dinner spot.",
    whatToOrder: ["Paella", "Patatas bravas", "Tapas to share"],
    tags: ["Downtown", "Date spot", "Sit-down"],
    image: "/images/aventura.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Aventura+Ann+Arbor",
  },
  {
    id: "mani_osteria_bar",
    name: "Mani Osteria",
    category: "restaurant",
    cuisine: "Italian",
    area: "Downtown",
    lat: 42.2795889,
    lng: -83.7442348,
    note: "Pizza, pasta, and a nicer downtown dinner feel.",
    whatToOrder: ["Wood-fired pizza", "Pasta", "Shared salad"],
    tags: ["Italian", "Downtown", "Sit-down"],
    image: "/images/mani_osteria_bar.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Mani+Osteria+Ann+Arbor",
  },
  {
    id: "pacific_rim_by_kana",
    name: "Pacific Rim by Kana",
    category: "restaurant",
    cuisine: "Asian",
    area: "Downtown",
    lat: 42.27995,
    lng: -83.74795,
    note: "Higher-end downtown dinner option for special occasions.",
    whatToOrder: ["Seafood entree", "Asian-inspired small plate", "Chef-style special"],
    tags: ["Asian", "Downtown", "Special occasion"],
    image: "/images/pacific_rim_by_kana.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Pacific+Rim+by+Kana+Ann+Arbor",
  },
  {
    id: "zingermans_delicatessen",
    name: "Zingerman's Delicatessen",
    category: "restaurant",
    cuisine: "Deli",
    area: "Kerrytown",
    lat: 42.2846981,
    lng: -83.7451513,
    note: "Classic Ann Arbor deli; best saved for when you want the local institution.",
    whatToOrder: ["Signature sandwich", "Pickle side", "Deli salad"],
    tags: ["Deli", "Kerrytown", "Worth the trip"],
    image: "/images/zingermans_delicatessen.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Zingerman%27s+Delicatessen+Ann+Arbor",
  },
  {
    id: "culantro",
    name: "Culantro",
    category: "restaurant",
    cuisine: "Peruvian",
    area: "Kerrytown",
    lat: 42.2831511,
    lng: -83.7486366,
    note: "Casual Peruvian option near Kerrytown and Main Street.",
    whatToOrder: ["Lomo saltado", "Pollo dish", "Empanada"],
    tags: ["Peruvian", "Kerrytown", "Casual"],
    image: "/images/culantro.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Culantro+Ann+Arbor",
  },
  {
    id: "hop_cat",
    name: "HopCat",
    category: "drinks",
    cuisine: "Bar food",
    area: "Downtown",
    lat: 42.2789296,
    lng: -83.7418442,
    note: "Burger and beer spot downtown; better for a group night than quick food.",
    whatToOrder: ["Cosmik fries", "Burger", "Shareable appetizer"],
    tags: ["Drinks", "Downtown", "Group"],
    image: "/images/hop_cat.webp",
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=HopCat+Ann+Arbor",
  },
  {
    id: "michigan_theater",
    name: "Michigan Theater",
    category: "things",
    area: "Downtown",
    lat: 42.2794895,
    lng: -83.7417499,
    note: "A polished downtown movie/event option when you want a non-food plan.",
    tags: ["Movies", "Downtown", "Classic"],
    image: "/images/umich.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Michigan+Theater+Ann+Arbor",
  },
  {
    id: "nichols_arboretum",
    name: "Nichols Arboretum",
    category: "things",
    area: "East Campus",
    lat: 42.2790761,
    lng: -83.7223751,
    note: "Best low-effort nature escape close to campus.",
    tags: ["Walk", "Nature", "Reset"],
    image: "/images/nichols_arboretum.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Nichols+Arboretum+Ann+Arbor",
  },
  {
    id: "michigan_union",
    name: "Michigan Union",
    category: "things",
    area: "Central Campus",
    lat: 42.2751698,
    lng: -83.7415127,
    note: "Central Campus landmark and easy meeting point.",
    tags: ["Central Campus", "Landmark", "Meeting point"],
    image: "/images/michigan_union.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Michigan+Union+Ann+Arbor",
  },
  {
    id: "pierpont_commons",
    name: "Pierpont Commons",
    category: "things",
    area: "North Campus",
    lat: 42.2911194,
    lng: -83.7176029,
    note: "North Campus student hub and useful landmark.",
    tags: ["North Campus", "Landmark", "Study"],
    image: "/images/pierpont_commons.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Pierpont+Commons+Ann+Arbor",
  },
  {
    id: "duderstadt_library",
    name: "Duderstadt Center",
    category: "things",
    area: "North Campus",
    lat: 42.2911757,
    lng: -83.715767,
    note: "North Campus study and project hub.",
    tags: ["North Campus", "Study", "Landmark"],
    image: "/images/duderstadt_library.webp",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Duderstadt+Center+Ann+Arbor",
  },
];

export const defaultPick = kisaPicks[0];
